name: Tests, Package, and Deployment

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ["v*"]

# cancel previous job if new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PKG_NAME: drtsans

jobs:
  #################
  ### Run Tests ###
  #################

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4

      - name: Install chromium
        run: |
          echo "chromium enables testing HTML reports"
          sudo apt-get install --yes chromium-browser

      - name: Run unit tests
        run: |
          pixi run versioningit -w
          git submodule update --init
          pixi run unit-test
          mv .coverage .coverage.unit

      - name: Run integration tests
        run: |
          # TODO: change back to running tests in parallel after the mantid memory leak has been patched (EWM 14083)
          # pixi run test -vv -m "not mount_eqsans" --dist loadscope -n 2 --cov=src --cov-report=xml:integration_test_coverage.xml --cov-report=term-missing --junitxml=integration_test_results.xml tests/integration/
          pixi run integration-test
          mv .coverage .coverage.integration

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  ##############################
  ### Package and Deployment ###
  ##############################

  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4

      - name: Build Conda package
        run: |
          pixi run conda-build
          mkdir -p /tmp/local-channel/linux-64
          cp *.conda /tmp/local-channel/linux-64

      - name: Verify conda package
        uses: neutrons/conda-verify@main
        with:
          package-name: drtsans
          local-channel: /tmp/local-channel
          python-version: "3.11"
          extra-channels: mantid neutrons
          extra-commands: python -c "import drtsans"
            python -c "import mantid"

      - name: Upload conda package as artifact
        uses: actions/upload-artifact@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: artifact-conda-package
          path: ${{ env.PKG_NAME }}-*.conda

  publish:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    needs: [tests, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4

      - name: Download conda package artifact
        uses: actions/download-artifact@v7
        with:
          name: artifact-conda-package

      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          pixi run anaconda upload --label $CONDA_LABEL --user neutrons ${{ env.PKG_NAME }}-*.conda

  # Trigger GitLab dev deploy pipeline
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/next'
    steps:
      - name: Get Environment Name
        uses: neutrons/branch-mapper@main
        id: env_name
        with:
          prefix: drtsans

      - name: Trigger Dev Deploy
        # use https://github.com/eic/trigger-gitlab-ci/pull/14 until merged
        uses: eic/trigger-gitlab-ci@d984d8d53d871d2fdc1325639d94322da6e8747f
        id: trigger
        with:
          url: https://code.ornl.gov
          project_id: 18099
          ref_name: main
          token: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

      - name: Annotate commit
        uses: peter-evans/commit-comment@v4
        with:
          body: |
            GitLab pipeline for ${{ steps.env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
